export const GET_ALL_TRANSACTION='GET_ALL_TRANSACTION';
export const FILTER_TRANSACTION='FILTER_TRANSACTION';
export const GOTO_PAGE='GOTO_PAGE';
export const SELECT_TRANSACTION='SELECT_TRANSACTION';
